# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d9f75bf2ecea720173dc400c0c7e678779633215e4fbc68a69bec5edc92ee8f54fd01f2a1811f8f15ea37409ced4b8ef3dceb2991ba443bd29e99760ffca9c47

test:
  secret_key_base: 0c58246c193b19607eb4027d03dd448cd85a49e44bb94a4082bfcde9346a2b0b0ea61a4c7e4be7c73f738493d1171c2d998d093f032529e38879dd3a42474b1c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
